### ISSUE TITLE
Create a nice 404 page for when an incorrect route is entered

### ISSUE THREAD

**Issue by moosichu** [hackersatcambridge/hac-website#78] opened 2017-10-06 08:07 UTC
See issue #58 for the backend needed for this.

When someone goes to [https://hackersatcambridge.com/hot-hot-hotdogs](https://hackersatcambridge.com/hot-hot-hotdogs) (or any other invalid route), you get something similar to:

![Screen Of Webpage Showing "Cannot GET /hot-hot-hotdogs."](https://user-images.githubusercontent.com/10348641/31521345-0f67a504-afa1-11e7-967c-be948e58458b.png)

Which is naturally incredibly ugly and unhelpful, with no way of navigating to a valid page.

Ideally we want a nicely themed 404 page. This issue is purely for creating the visuals of such a page, #58 is about the backend system to route to such a page.

**Comment by moosichu** [comment] 2017-10-12 22:05
@Pinpickle Is this actually a good first issue, and if so what is the best place to get started?

**Comment by Pinpickle** [comment] 2017-10-12 22:16
@moosichu firstly this is a dupe of #58, but it probably benefits from being split up - we'd just need to edit the original issue.

This one would require ramping up of both templating (rendering the 404 page) and routing (catching the unfound route). Maybe we should split this up into the template and the routing?

**Comment by moosichu** [comment] 2017-10-12 22:34
@Pinpickle Gonna make this the templating one then

**Comment by Pinpickle** [comment] 2017-10-15 16:37
Fixed by #86 (including the routing!)

**Closed by Pinpickle** 2017-10-15 16:37 UTC
Labels: frontend, good first issue, priority medium
